use crate::game::{Game, GameState};
use crate::llm::{generate_trivia_questions, Question};
use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::sync::Arc;
use tokio::sync::RwLock;
use uuid::Uuid;

const SAVE_DIR: &str = "game_saves"; // Directory to save game states

fn parse_generated_questions(json_text: &str) -> Result<Vec<Question>, Box<dyn std::error::Error>> {
    let parsed: serde_json::Value = serde_json::from_str(json_text)?;
    
    let questions_array = parsed.get("questions")
        .and_then(|q| q.as_array())
        .ok_or("No 'questions' array found in response")?;
    
    let mut questions = Vec::new();
    
    for question_obj in questions_array {
        let question_text = question_obj.get("question")
            .and_then(|q| q.as_str())
            .ok_or("Missing 'question' field")?;
        
        let answer_text = question_obj.get("answer")
            .and_then(|a| a.as_str())
            .ok_or("Missing 'answer' field")?;
        
        questions.push(Question {
            question: question_text.to_string(),
            answer: answer_text.to_string(),
        });
    }
    
    Ok(questions)
}

#[derive(Debug, Default)]
pub struct GameManager {
    games: HashMap<String, Arc<RwLock<Game>>>,
    // save_path: String, // Path to the file where games are saved, if needed
}

impl GameManager {
    pub fn new() -> Self {
        let mut manager = Self {
            games: HashMap::new(),
            // save_path: "games.json".to_string(), // Example save file
        };
        fs::create_dir_all(SAVE_DIR).expect("Failed to create save directory");
        manager.load_all_games().unwrap_or_else(|e| {
            eprintln!("Failed to load games: {}. Starting with an empty set.", e);
            // Proceed with an empty set of games if loading fails
        });
        manager
    }

    pub async fn create_game(
        &mut self,
        category: String,
        difficulty: u8,
        num_of_questions: u32,
        age_group: String,
        hint_level: u8,
    ) -> Result<String, String> {
        let questions_text = generate_trivia_questions()
            .await
            .map_err(|e| format!("Failed to generate trivia questions: {}", e))?;

        // Parse the questions from the LLM response
        let questions = parse_generated_questions(&questions_text)
            .map_err(|e| format!("Failed to parse questions: {}", e))?;

        if questions.is_empty() {
            return Err("No questions were generated by the LLM.".to_string());
        }

        let game_id = Uuid::new_v4().to_string();
        let game = Game::new(
            game_id.clone(),
            questions,
            category,
            difficulty,
            num_of_questions,
            age_group,
            hint_level,
        );
        
        // Save the game before wrapping in Arc<RwLock>
        self.save_game(&game_id, &game).await
            .map_err(|e| e.to_string())?;
            
        let game_arc = Arc::new(RwLock::new(game));
        self.games.insert(game_id.clone(), game_arc);
        Ok(game_id)
    }

    pub async fn get_game(&self, game_id: &str) -> Option<Arc<RwLock<Game>>> {
        self.games.get(game_id).cloned()
    }

    pub async fn add_player_to_game(&self, game_id: &str, player_id: String) -> Result<(), String> {
        match self.games.get(game_id) {
            Some(game_arc) => {
                let mut game = game_arc.write().await;
                let result = game.add_player(player_id);
                if result.is_ok() {
                    self.save_game(game_id, &game).await.map_err(|e| e.to_string())?;
                }
                result
            }
            None => Err(format!("Game with ID {} not found.", game_id)),
        }
    }

    pub async fn start_game_loop(&self, game_id: &str) -> Result<(), String> {
        match self.games.get(game_id) {
            Some(game_arc) => {
                let mut game = game_arc.write().await;
                let result = game.start_game();
                 if result.is_ok() {
                    self.save_game(game_id, &game).await.map_err(|e| e.to_string())?;
                }
                result
            }
            None => Err(format!("Game with ID {} not found.", game_id)),
        }
    }

    pub async fn submit_player_answer(
        &self,
        game_id: &str,
        player_id: &str,
        answer: &str,
    ) -> Result<crate::llm::AnswerCorrectness, String> {
        match self.games.get(game_id) {
            Some(game_arc) => {
                // Call the associated function handle_submission on the Game struct
                let correctness = Game::handle_submission(Arc::clone(game_arc), player_id, answer).await?;
                // Save game state after answer submission
                let game_data_to_save = game_arc.read().await;
                self.save_game(game_id, &game_data_to_save).await.map_err(|e| e.to_string())?;
                Ok(correctness)
            }
            None => Err(format!("Game with ID {} not found.", game_id)),
        }
    }

    pub async fn advance_to_next_question(&self, game_id: &str) -> Result<Option<Question>, String> {
        match self.games.get(game_id) {
            Some(game_arc) => {
                let mut game = game_arc.write().await;
                let question_option = game.next_question()?;
                let question_clone = question_option.cloned();
                
                // Save after getting the question but before dropping the write lock
                self.save_game(game_id, &*game).await
                    .map_err(|e| e.to_string())?;
                    
                Ok(question_clone)
            }
            None => Err(format!("Game with ID {} not found.", game_id)),
        }
    }

    pub async fn end_game_round(&self, game_id: &str) -> Result<(), String> {
        match self.games.get(game_id) {
            Some(game_arc) => {
                let mut game = game_arc.write().await;
                game.end_round();
                self.save_game(game_id, &game).await.map_err(|e| e.to_string())?;
                Ok(())
            }
            None => Err(format!("Game with ID {} not found.", game_id)),
        }
    }

    pub async fn get_game_state(&self, game_id: &str) -> Result<GameState, String> {
        match self.games.get(game_id) {
            Some(game_arc) => {
                let game = game_arc.read().await;
                Ok(game.state.clone())
            }
            None => Err(format!("Game with ID {} not found.", game_id)),
        }
    }

    pub async fn get_game_summary(&self, game_id: &str) -> Result<HashMap<String, i32>, String> {
        match self.games.get(game_id) {
            Some(game_arc) => {
                let game = game_arc.read().await;
                Ok(game.get_game_summary())
            }
            None => Err(format!("Game with ID {} not found.", game_id)),
        }
    }

    async fn save_game(&self, game_id: &str, game: &Game) -> Result<(), std::io::Error> {
        let file_path = Path::new(SAVE_DIR).join(format!("{}.json", game_id));
        let game_json = serde_json::to_string_pretty(game)?;
        fs::write(file_path, game_json)
    }

    fn load_game(&mut self, file_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
        let game_json = fs::read_to_string(file_path)?;
        let game: Game = serde_json::from_str(&game_json)?;
        let game_id = game.id.clone();
        self.games.insert(game_id, Arc::new(RwLock::new(game)));
        Ok(())
    }

    pub fn load_all_games(&mut self) -> Result<(), Box<dyn std::error::Error>> {
        let path = Path::new(SAVE_DIR);
        if path.exists() && path.is_dir() {
            for entry in fs::read_dir(path)? {
                let entry = entry?;
                let path = entry.path();
                if path.is_file() && path.extension().and_then(std::ffi::OsStr::to_str) == Some("json") {
                    if let Err(e) = self.load_game(&path) {
                        eprintln!("Failed to load game from {:?}: {}", path, e);
                        // Optionally, decide if one failed load should stop all, or just skip.
                    }
                }
            }
        }
        Ok(())
    }

    // Maybe a function to clean up old/finished games from memory and disk
    pub async fn remove_game(&mut self, game_id: &str) -> Result<(), String> {
        if self.games.remove(game_id).is_some() {
            let file_path = Path::new(SAVE_DIR).join(format!("{}.json", game_id));
            if file_path.exists() {
                fs::remove_file(file_path).map_err(|e| format!("Failed to delete game save file: {}", e))?;
            }
            Ok(())
        } else {
            Err(format!("Game with ID {} not found for removal.", game_id))
        }
    }
}
